[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
position.x = 350
position.y = 250
dimensions.columns = 120
dimensions.lines = 30

[font]
size = 14.0

normal.family = "JetBrainsMono Nerd Font"
